# cna't work with rootless mode because must use network_mode host
version: '3.9'

services:
  cache:
    image: redis/redis-stack:latest
    ports:
      - 6379:6379
      - 8001:8001

  db:
    image: postgres:16-alpine
    ports:
      - 5432:5432
    volumes:
      - ./docker-data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: roxavn

  seaweedfs-s3:
    image: chrislusf/seaweedfs
    container_name: seaweedfs-s3
    ports:
      - "8333:8333"
    volumes:
      - ./docker-data/seaweed:/data
    entrypoint: /bin/sh -c
    command: |
      "echo '{
        \"identities\": [
          {
            \"name\": \"anonymous\",
            \"actions\": [
              \"Read:bucket/public/*\"
            ]
          },
          {
            \"name\": \"admin_user\",
            \"credentials\": [
              {
                \"accessKey\": \"some_access_key1\",
                \"secretKey\": \"some_secret_key1\"
              }
            ],
            \"actions\": [
              \"Admin\",
              \"Read\",
              \"List\",
              \"Tagging\",
              \"Write\"
            ]
          }
        ]
      }' > /etc/seaweedfs/config.json && \
      weed server -s3 -s3.config /etc/seaweedfs/config.json"
