# cna't work with rootless mode because must use network_mode host
version: '3.9'

services:
  cache:
    image: redis/redis-stack:latest
    restart: on-failure
    ports:
      - 6379:6379
      - 8001:8001

  db:
    image: postgres:14-alpine
    restart: on-failure
    ports:
      - 5434:5432
    volumes:
      - ./docker-data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: roxavn

  seaweed_master:
    image: chrislusf/seaweedfs
    network_mode: 'host'
    command: 'master -ip=localhost -ip.bind=0.0.0.0 -metricsPort=9324'

  seaweed_volume:
    image: chrislusf/seaweedfs
    network_mode: 'host'
    volumes:
      - ./docker-data/seaweed:/data
    command: 'volume -mserver="localhost:9333" -ip.bind=0.0.0.0 -port=28080 -publicUrl="http://localhost:28080" -metricsPort=9325'
    depends_on:
      - seaweed_master
