version: '3.9'

services:
  db:
    image: postgres:14-alpine
    restart: on-failure
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: example

  seaweed_master:
    image: chrislusf/seaweedfs
    ports:
      - 9333:9333
      - 19333:19333
      - 9324:9324
    command: 'master -ip=seaweed_master -ip.bind=0.0.0.0 -metricsPort=9324'

  seaweed_volume:
    image: chrislusf/seaweedfs
    ports:
      - 28080:28080
      - 18080:18080
      - 9325:9325
    command: 'volume -mserver="seaweed_master:9333" -ip.bind=0.0.0.0 -port=28080 -publicUrl="localhost:28080"  -metricsPort=9325'
    depends_on:
      - seaweed_master
