services:
  db:
    image: postgres:14-alpine
    restart: on-failure
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: example
