#!/bin/bash

folders=(
    "packages/core"
    "packages/dev-web"
    "packages/cli"
    "packages/module-system"
    "packages/module-user"
    "packages/module-insight"
    "packages/module-upload"
    "packages/module-installer"
    "packages/module-message"
    "packages/module-notification"
    "packages/module-project"
    "packages/module-web3"
    "packages/module-asset"
    "packages/module-currency"
    "packages/module-location"
    "packages/plugin-barcode"
    "packages/plugin-excel"
    "packages/plugin-qr-code"
    "packages/plugin-sequence"
    "packages/plugin-classification"
    "packages/module-accounting"
    "packages/module-socket"
    # "packages/module-game"
    "packages/module-referral"
    "packages/module-workflow"
    "packages/module-reward"
    "packages/module-wager"
    "packages/plugin-asset-template"
    "packages/module-order"
    "packages/module-skill"
    "packages/module-timesheet"
    "packages/module-organization"
    "packages/module-finance-contract"
    # "packages/module-follow"
    "packages/plugin-api-logger"
    "packages/plugin-api-rate-limiter"
    "packages/plugin-otp"
    "packages/plugin-email-sender"
    "packages/plugin-auth-email"
    "packages/plugin-auth-web3"
    "packages/plugin-auth-webauthn"
    "packages/plugin-auth-two-factor"
    "packages/plugin-identity-pin"
    "packages/plugin-identity-totp"
    "packages/plugin-auth-two-factor-totp"
    "packages/plugin-reauth-password"
    "packages/plugin-payment"
    # "packages/plugin-payment-web3"
    "packages/plugin-project-notification"
    "packages/plugin-project-message"
    "packages/plugin-firebase"
    "packages/plugin-auth-firebase"
    # "packages/plugin-asset-web3"
    "packages/plugin-asset-category"
    "packages/plugin-user-ban"
    "packages/plugin-user-identity-limit"
    "packages/plugin-web3-airdrop"
    "packages/plugin-store-record"
    # "packages/plugin-casino-game"
    "packages/plugin-telegram-bot"
    "packages/plugin-message-report"
    "packages/plugin-message-reaction"
    "packages/plugin-message-pin"
    "packages/plugin-message-media"
    "packages/plugin-message-poll"
    "packages/plugin-message-notification"
    "packages/plugin-message-realtime"
    "packages/plugin-message-conversation"
    "packages/plugin-notification-in-app"
    "packages/plugin-notification-push"
    "packages/plugin-notification-push-web"
    "packages/plugin-location-countries"
    "packages/plugin-location-vietnam"
    "packages/plugin-location-address"
    "packages/plugin-presence-redis"
    "packages/plugin-news"
    "packages/plugin-openapi"
    "packages/plugin-order-barcode"
    "packages/plugin-job-custom"
    "packages/plugin-job-logger"
    "packages/plugin-ui-editor-export"
)

for dir in "${folders[@]}"; do
    if [ -d "$dir" ]; then
        echo "📂 Processing folder: $dir"
        cd "$dir"
        # rm -rf dist
        # npx roxavn migration:up
        # npx roxavn sync
        # npm run build
        npx standard-version --release-as 3.9.0
        git push --follow-tags origin main && npm publish
        cd - > /dev/null
    else
        echo "⚠️ Folder not found: $dir"
    fi
done

echo "✅ Done!"
